language: c

os: linux
dist: trusty


compiler: arm-none-eabi-gcc


before_install:
    sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
    sudo apt-get update
    sudo apt-get install gcc-arm-embedded
